name: Binary Ready - Veracode Static Code Analysis

run-name: Binary Ready - Static Code Analysis - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [binary-ready-veracode-sast-pipeline-scan]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: a-karthik-bharadwaj-org/veracode-github-app@main
      id: 'create_check_run'
      with:
        name: ${{ github.workflow }}
        head_sha: ${{ github.event.client_payload.sha }}
        owner: ${{ github.event.client_payload.repository.owner }}
        repo: ${{ github.event.client_payload.repository.name }}
        status: 'in_progress'
        event_type: ${{ github.event.client_payload.event_type }}
        github_token: ${{ github.event.client_payload.token }}
        
  pipeline_scan:
    needs: register
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        run_id: ${{ github.event.client_payload.run_id }}
        repo: ${{ github.event.client_payload.repository.full_name }}
    - name: Get the name of the downloaded files
      run: |
        artifact_file=$(ls -1 ./veracode-artifact | head -n 1)
        echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
    - name: Veracode Pipeline-Scan
      id: pipeline-scan
      uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.4
      with:
        vid: ${{ secrets.API_ID }}
        vkey: ${{ secrets.API_KEY }}
        file: ./veracode-artifact/${{ env.veracode_artifact }}
        fail_build: true
