name: Veracode Static Pipeline Scanner
on:
  workflow_call:
permissions:
    checks: write
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump GitHub Repository context
      env:
        GITHUB_REPO_CONTEXT: ${{ toJson(github.repository) }}
      run: echo "$GITHUB_REPO_CONTEXT"
    - name: Dump GitHub Event Repository context
      env:
        GITHUB_EVENT_REPO_CONTEXT: ${{ toJson(github.event.repository) }}
      run: echo "$GITHUB_EVENT_REPO_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Show default environment variables
      run: |
        echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
        echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
        echo "The run id is: $GITHUB_RUN_ID"
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"
        echo "GitHub SHA: $GITHUB_SHA"
    - name: Setup the project
      uses: a-karthik-bharadwaj-org/veracode-github-app@main
      id: 'create_check_run'
      with:
        head_sha: ${{ github.sha }}
        owner: ${{ github.event.client_payload.repository.owner }}
        repo: ${{ github.event.client_payload.repository.name }}
        name: 'Check for Pipeline Scan'
        status: 'in_progress'
        event_type: 'pipeline scan'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo '${{ steps.create_check_run.outputs.data }}'"
  pipeline_scan:
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV

      # run the pipeline scan action
      - name: Veracode Pipeline-Scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.4
        with:
          vid: ${{ secrets.API_ID }}
          vkey: ${{ secrets.API_KEY }}
          file: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          fail_build: true
