name: Veracode Software Composition Analysis

run-name: Software Composition Analysis - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [veracode-sca-scan]
    
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: a-karthik-bharadwaj-org/veracode-github-app@main
      id: 'create_check_run'
      with:
        name: ${{ github.workflow }}
        head_sha: ${{ github.event.client_payload.sha }}
        owner: ${{ github.event.client_payload.repository.owner }}
        repo: ${{ github.event.client_payload.repository.name }}
        status: 'in_progress'
        event_type: ${{ github.event.client_payload.event_type }}
        github_token: ${{ github.event.client_payload.token }}
       
  veracode-sca-scan:
    needs: [register]
    runs-on: ubuntu-latest
    name: Veracode Component Analysis

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false  
#           fail-on-cvss: 1
#           min-cvss-for-issue: 1
